# Generated by Django 3.0.5 on 2020-07-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyNotes_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes_model',
            name='notes_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
