# Generated by Django 3.0.5 on 2020-07-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyNotes_App', '0004_mynotes_model_notes_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynotes_model',
            name='notes_archived',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
