# Generated by Django 3.1 on 2020-08-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyNotes_App', '0005_mynotes_model_notes_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes_model',
            name='notes_created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
