# Generated by Django 3.1 on 2020-09-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyNotes_App', '0006_auto_20200830_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes_model',
            name='notes_created_date',
            field=models.DateField(),
        ),
    ]
