# Generated by Django 3.1 on 2020-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyNotes_App', '0007_auto_20200902_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynotes_model',
            name='notes_user',
            field=models.TextField(null=True),
        ),
    ]
