# Generated by Django 3.1 on 2020-09-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyNotes_App', '0008_mynotes_model_notes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes_model',
            name='notes_user',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
