# Generated by Django 3.1 on 2020-09-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyNotes_App', '0009_auto_20200918_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynotes_model',
            name='notes_user',
        ),
        migrations.AddField(
            model_name='mynotes_model',
            name='notes_username',
            field=models.CharField(default='Yathindra', max_length=150),
        ),
        migrations.AlterField(
            model_name='mynotes_model',
            name='notes_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
